version: '3'

services:

  ruby:
    build: ./
    image: ruby-sinatra
    volumes:
      - .:/app
    container_name: ruby.holybible
    ports:
      - "8080:3000"
    entrypoint: ruby app.rb -p 3000 -o 0.0.0.0